### ISSUE TITLE
Chain registry discrepancy

### ISSUE THREAD

**Issue by greg-szabo** [tenet-org/tenet-public#92]
## Summary of Bug
The Tenet entry in the [chain registry](https://github.com/cosmos/chain-registry/blob/master/tenet/chain.json) points to a version of the binary (v11.2.0) that doesn't have a tag in the source code.

I can also see that the binary has been released in the tenet-mainnet repository.

## Version
v11.2.0

## Additional context
I'm part of the security incident response team for the Cosmos Ecosystem. I'm cleaning up the chain registry so we can report on the used versions of the core libraries maintained by the ecosystem. (Comet, Cosmos SDK, WASM, IBC, etc). The purpose is to set up a vulnerability response process where networks get updates when a security fix has been released for these libraries.

For this, we need the URL to the source code and the tag of the used version of the source. (Right now we just scan the `go.mod` file but this might change in the future.)

## Proposed fix
1. Tag the v11.2.0 release in the source code.
2. Change the `git_repo` section in the chain registry to the source code repository (`https://github.com/tenet-org/tenet-public`)
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Ejeziemsam** [comment]
Hi,
Please I need help, I sent my tenet token to my tangem wallet but I can't find it there

**Comment by Ejeziemsam** [comment]
Please how do I get my tenet back to my onekey wallet. I send some of it from onekey to Tangum wallet  Eth-Tenet but I didn't receive it and I checked on tenet online it's in my Eth-tenet as my balance but not showing in my wallet

**Comment by greg-szabo** [comment]
I've sent an email to Everstake, one of the bigger Tenet validators for help:

From: greg
To: security@everstake.one

Hi,

I’m doing security reporting on the core libraries underlying Cosmos-based blockchain networks with the core development teams. I’ve reached out to Tenet on their public repository for a chain registry update so they can be included in the report. They have not responded to the issue since August.

As a validator to the Tenet network, could you please submit an update to the chain registry that points the Tenet entry to the right binary version?

Here is the GitHub issue with more details: https://github.com/tenet-org/tenet-public/issues/92

Here’s a public report of different networks’ underlying library versions based on the chain registry: https://peek.informal.systems/

Regards,
greg

**Comment by greg-szabo** [comment]
Thanks for @reversesigh for updating the version number in the chain registry.
